# SPDX-FileCopyrightText: Copyright (c) 2020-2025 Objectionary
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: build
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: npm install -g eolang
    - run: make
    - run: make run
